sudo: required
services:
  - docker

before_install:
  - docker build -t alexandryz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexandryz/react-test npm test -- --coverage

after_success:
  - docker build -t alexandryz/multi-client ./client
  - docker build -t alexandryz/multi-nginx ./nginx
  - docker build -t alexandryz/multi-server ./server
  - docker build -t alexandryz/multi-worker ./worker

 # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push alexandryz/multi-client
  - docker push alexandryz/multi-nginx
  - docker push alexandryz/multi-server
  - docker push alexandryz/multi-worker